const ICON_TYPES = {
  arrow: 'arrow',
  google: 'google',
  facebook: 'facebook',
  eye: 'eye',
  hidden: 'hidden',
  checked: 'checked',
  unchecked: 'unchecked',
  user: 'user',
  success: 'success',
  logoHeader: 'logo-header',
  logoFooter: 'logo-footer',
  logoHeaderText: 'logo-header-text',
  info: 'info',
  filter: 'filter',
  plus: 'plus',
  minus: 'minus',
  logout: 'logout',
  search: 'search',
  category: 'category',
  education: 'education',
  contacts: 'contacts',
};

export default ICON_TYPES;
